fix: warn when clipping, gen agent id once
hexedtech/codemp pull request #38
Opened 2024-10-02 22:22 UTC by alemidev

2024-10-06 00:45 UTC, ghyatzo reviewed
The clipping behavior was already present. Was this to just have print a warning?

2024-10-06 00:46 UTC, ghyatzo reviewed
Good catch on the agent id.

2024-10-08 21:05 UTC, zaaarf approved these changes

2024-10-08 21:06 UTC, zaaarf requested changes
Needs to be rebased onto `dev`. @alemidev should do it, to preserve authorship.

2024-10-11 21:21 UTC, zaaarf approved these changes

2024-10-11 21:21 UTC, merged